{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "f3842997-f1c5-4045-8867-760b49bdbc5b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Welcome to Brain Games!\n",
      "\n",
      "    Brain Games\n",
      "     _---~~(~~-_.\n",
      "    _{        )   )\n",
      "  ,   ) -~~- ( ,-' )_\n",
      " (  `-,_..`., )-- '_,)\n",
      "( ` _)  (  -~( -_ `,  }\n",
      "(_-  _  ~_-~~~~`,  ,' )\n",
      "  `~ -^(    __;-,((()))\n",
      "        ~~~~ {_ -_(())\n",
      "               `\\  }\n",
      "                 { }\n",
      "\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Please Enter User Name: Bill\n",
      "Start Game? Yes/No :  Yes\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The computer will try to guess a number you are thinking of.\n",
      "Please give the computer a range for which your number will fall in between\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Please enter SMALLEST number for the range of numbers your number will fall in: 1\n",
      "Please enter the LARGEEST number for the range of number your number will fall in: 2\n",
      "Please enter your number: 2\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Hiding your number from computer...\n",
      "Computer guess is.....\n",
      "1\n",
      "Computer guessed wrong!\n",
      "Congratulations, Bill ! You won!\n",
      "\n",
      "                      *    *\n",
      "   *         '       *       .  *   '     .           * *\n",
      "                                                               '\n",
      "       *                *'          *          *        '\n",
      "   .           *               |               /\n",
      "               '.         |    |      '       |   '     *\n",
      "                 \\*        \\   \\             /\n",
      "       '          \\     '* |    |  *        |*                *  *\n",
      "            *      `.       \\   |     *     /    *      '\n",
      "  .                  \\      |   \\          /               *\n",
      "     *'  *     '      \\      \\   '.       |\n",
      "        -._            `                  /         *\n",
      "  ' '      ``._   *                           '          .      '\n",
      "   *           *\\*          * .   .      *\n",
      "*  '        *    `-._                       .         _..:='        *\n",
      "             .  '      *       *    *   .       _.:--'\n",
      "          *           .     .     *         .-'         *\n",
      "   .               '             . '   *           *         .\n",
      "  *       ___.-=--..-._     *                '               '\n",
      "                                  *       *\n",
      "                *        _.'  .'       `.        '  *             *\n",
      "     *              *_.-'   .'            `.               *\n",
      "                   .'                       `._             *  '\n",
      "   '       '                        .       .  `.     .\n",
      "       .                      *                  `\n",
      "               *        '             '                          .\n",
      "     .                          *        .           *  *\n",
      "             *        .                                    '\n",
      "            \n",
      "Wins: 1\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "would you like to try again? (Yes/No): Yes\n",
      "Please enter your number: 2\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Hiding your number from computer...\n",
      "Computer guess is.....\n",
      "2\n",
      "Computer guessed correctly!\n",
      "Sorry, Bill you lost! Try again.\n",
      "\n",
      "                                                                  ..\n",
      "                               ,,,                         MM .M\n",
      "                           ,!MMMMMMM!,                     MM MM  ,.\n",
      "   ., .M                .MMMMMMMMMMMMMMMM.,          'MM.  MM MM .M'\n",
      " . M: M;  M          .MMMMMMMMMMMMMMMMMMMMMM,          'MM,:M M'!M'\n",
      ";M MM M: .M        .MMMMMMMMMMMMMMMMMMMMMMMMMM,         'MM'...'M\n",
      " M;MM;M :MM      .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.       .MMMMMMMM\n",
      " 'M;M'M MM      MMMMMM  MMMMMMMMMMMMMMMMM  MMMMMM.    ,,M.M.'MMM'\n",
      "  MM'MMMM      MMMMMM @@ MMMMMMMMMMMMMMM @@ MMMMMMM.'M''MMMM;MM'\n",
      " MM., ,MM     MMMMMMMM  MMMMMMMMMMMMMMMMM  MMMMMMMMM      '.MMM\n",
      " 'MM;MMMMMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.      'MMM\n",
      "  ''.'MMM'  .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM       MMMM\n",
      "   MMC      MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.      'MMMM\n",
      "  .MM      :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM''MMM       MMMMM\n",
      "  MMM      :M  'MMMMMMMMMMMMM.MMMMM.MMMMMMMMMM'.MM  MM:M.    'MMMMM\n",
      " .MMM   ...:M: :M.'MMMMMMMMMMMMMMMMMMMMMMMMM'.M''   MM:MMMMMMMMMMMM'\n",
      "AMMM..MMMMM:M.    :M.'MMMMMMMMMMMMMMMMMMMM'.MM'     MM''''''''''''\n",
      "MMMMMMMMMMM:MM     'M'.M'MMMMMMMMMMMMMM'.MC'M'     .MM\n",
      " '''''''''':MM.       'MM!M.'M-M-M-M'M.'MM'        MMM\n",
      "            MMM.            'MMMM!MMMM'            .MM\n",
      "             MMM.             '''   ''            .MM'\n",
      "              MMM.                               MMM'\n",
      "               MMMM            ,.J.JJJJ.       .MMM'\n",
      "                MMMM.       'JJJJJJJ'JJJM   CMMMMM\n",
      "                  MMMMM.    'JJJJJJJJ'JJJ .MMMMM'\n",
      "                    MMMMMMMM.'  'JJJJJ'JJMMMMM'\n",
      "                      'MMMMMMMMM'JJJJJ JJJJJ'\n",
      "                         ''MMMMMMJJJJJJJJJJ'\n",
      "                                 'JJJJJJJJ'\n",
      "        \n",
      "Wins: 0\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "would you like to try again? (Yes/No): No\n"
     ]
    }
   ],
   "source": [
    "#Import pandas library package into jupyter lab\n",
    "\n",
    "import pandas\n",
    "pandas.__version__\n",
    "\n",
    "#Import Random library\n",
    "#Import Time for slweep functions\n",
    "\n",
    "import pylab\n",
    "import random\n",
    "import time\n",
    "\n",
    "#Game Greeting.\n",
    "#Text design for brain was found online)\n",
    "\n",
    "print (\"Welcome to Brain Games!\")\n",
    "time.sleep(2)\n",
    "print(\"\"\"\n",
    "    Brain Games\n",
    "     _---~~(~~-_.\n",
    "    _{        )   )\n",
    "  ,   ) -~~- ( ,-' )_\n",
    " (  `-,_..`., )-- '_,)\n",
    "( ` _)  (  -~( -_ `,  }\n",
    "(_-  _  ~_-~~~~`,  ,' )\n",
    "  `~ -^(    __;-,((()))\n",
    "        ~~~~ {_ -_(())\n",
    "               `\\  }\n",
    "                 { }\n",
    "\"\"\")\n",
    "\n",
    "time.sleep(2)\n",
    "player_name = input(\"Please Enter User Name:\" )\n",
    "\n",
    "#Instructions\n",
    "\n",
    "start = input(\"Start Game? Yes/No : \")\n",
    "\n",
    "#How the game is played.\n",
    "\n",
    "print(\"The computer will try to guess a number you are thinking of.\")\n",
    "time.sleep(2)\n",
    "print(\"Please give the computer a range for which your number will fall in between\")\n",
    "time.sleep(3)\n",
    "#Use will input the min and max number for our program generate random numbers\n",
    "min = int(input(\"Please enter SMALLEST number for the range of numbers your number will fall in:\"))\n",
    "max = int(input(\"Please enter the LARGEEST number for the range of number your number will fall in:\"))\n",
    "\n",
    "wins = 0\n",
    "#The will initiate and keep count of players wins\n",
    "\n",
    "while start == \"Yes\": #While loop for game to start/end/keep going\n",
    "    if start == \"No\":\n",
    "        exit(0)\n",
    "    playerNum = int(input(\"Please enter your number:\")) #Ask users for their number \n",
    "    ##Also converts user input to integer for the ccomputer to correctly asses\n",
    "    print(\"\\nHiding your number from computer...\")\n",
    "\n",
    "    time.sleep(2)\n",
    "\n",
    "    x = random.randint(min,max) #generates random number from the given range of numbers provided by the user\n",
    "    compGuess = x\n",
    "    print(\"Computer guess is.....\")\n",
    "    time.sleep(3)\n",
    "    print(compGuess)\n",
    "    \n",
    "    time.sleep(2)\n",
    "    \n",
    "    if x == playerNum: #Instructs program what to execute if comp guessed the number correctly\n",
    "        print\n",
    "        print(\"Computer guessed correctly!\")\n",
    "        time.sleep(1)\n",
    "        print(\"Sorry,\",player_name, \"you lost! Try again.\")\n",
    "        time.sleep(2)\n",
    "        print(\"\"\"\n",
    "                                                                  ..\n",
    "                               ,,,                         MM .M\n",
    "                           ,!MMMMMMM!,                     MM MM  ,.\n",
    "   ., .M                .MMMMMMMMMMMMMMMM.,          'MM.  MM MM .M'\n",
    " . M: M;  M          .MMMMMMMMMMMMMMMMMMMMMM,          'MM,:M M'!M'\n",
    ";M MM M: .M        .MMMMMMMMMMMMMMMMMMMMMMMMMM,         'MM'...'M\n",
    " M;MM;M :MM      .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.       .MMMMMMMM\n",
    " 'M;M'M MM      MMMMMM  MMMMMMMMMMMMMMMMM  MMMMMM.    ,,M.M.'MMM'\n",
    "  MM'MMMM      MMMMMM @@ MMMMMMMMMMMMMMM @@ MMMMMMM.'M''MMMM;MM'\n",
    " MM., ,MM     MMMMMMMM  MMMMMMMMMMMMMMMMM  MMMMMMMMM      '.MMM\n",
    " 'MM;MMMMMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.      'MMM\n",
    "  ''.'MMM'  .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM       MMMM\n",
    "   MMC      MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.      'MMMM\n",
    "  .MM      :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM''MMM       MMMMM\n",
    "  MMM      :M  'MMMMMMMMMMMMM.MMMMM.MMMMMMMMMM'.MM  MM:M.    'MMMMM\n",
    " .MMM   ...:M: :M.'MMMMMMMMMMMMMMMMMMMMMMMMM'.M''   MM:MMMMMMMMMMMM'\n",
    "AMMM..MMMMM:M.    :M.'MMMMMMMMMMMMMMMMMMMM'.MM'     MM''''''''''''\n",
    "MMMMMMMMMMM:MM     'M'.M'MMMMMMMMMMMMMM'.MC'M'     .MM\n",
    " '''''''''':MM.       'MM!M.'M-M-M-M'M.'MM'        MMM\n",
    "            MMM.            'MMMM!MMMM'            .MM\n",
    "             MMM.             '''   ''            .MM'\n",
    "              MMM.                               MMM'\n",
    "               MMMM            ,.J.JJJJ.       .MMM'\n",
    "                MMMM.       'JJJJJJJ'JJJM   CMMMMM\n",
    "                  MMMMM.    'JJJJJJJJ'JJJ .MMMMM'\n",
    "                    MMMMMMMM.'  'JJJJJ'JJMMMMM'\n",
    "                      'MMMMMMMMM'JJJJJ JJJJJ'\n",
    "                         ''MMMMMMJJJJJJJJJJ'\n",
    "                                 'JJJJJJJJ'\n",
    "        \"\"\")\n",
    "        time.sleep(2)\n",
    "        wins = 0\n",
    "        print(\"Wins:\", (wins)) #reports the winning streak\n",
    "        time.sleep(2)\n",
    "        start = input(\"would you like to try again? (Yes/No):\") #Ask users if they would like to play again\n",
    "    else: #Instructs program what to execute if comp guessed the number incorrectly\n",
    "        print\n",
    "        print(\"Computer guessed wrong!\")\n",
    "        time.sleep(1)\n",
    "        print(\"Congratulations,\",player_name,\"! You won!\")\n",
    "        time.sleep(2)\n",
    "        print(\"\"\"\n",
    "                      *    *\n",
    "   *         '       *       .  *   '     .           * *\n",
    "                                                               '\n",
    "       *                *'          *          *        '\n",
    "   .           *               |               /\n",
    "               '.         |    |      '       |   '     *\n",
    "                 \\*        \\   \\             /\n",
    "       '          \\     '* |    |  *        |*                *  *\n",
    "            *      `.       \\   |     *     /    *      '\n",
    "  .                  \\      |   \\          /               *\n",
    "     *'  *     '      \\      \\   '.       |\n",
    "        -._            `                  /         *\n",
    "  ' '      ``._   *                           '          .      '\n",
    "   *           *\\*          * .   .      *\n",
    "*  '        *    `-._                       .         _..:='        *\n",
    "             .  '      *       *    *   .       _.:--'\n",
    "          *           .     .     *         .-'         *\n",
    "   .               '             . '   *           *         .\n",
    "  *       ___.-=--..-._     *                '               '\n",
    "                                  *       *\n",
    "                *        _.'  .'       `.        '  *             *\n",
    "     *              *_.-'   .'            `.               *\n",
    "                   .'                       `._             *  '\n",
    "   '       '                        .       .  `.     .\n",
    "       .                      *                  `\n",
    "               *        '             '                          .\n",
    "     .                          *        .           *  *\n",
    "             *        .                                    '\n",
    "            \"\"\")\n",
    "        time.sleep(2)\n",
    "        wins += 1 # adds to winning streak\n",
    "        print(\"Wins:\", (wins))\n",
    "        time.sleep(2)\n",
    "        start = input(\"would you like to try again? (Yes/No):\")#Asks user if they would like to play again "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ceb7ddab-d03b-4f3f-94d6-e371e17fe428",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
